### ISSUE TITLE
Can't start the example

### ISSUE THREAD

**Issue by luebken** [circleci/docker-elasticsearch#4]
I've [forked](https://github.com/luebken/docker-elasticsearch) the example and the build stops with the error: 

```
docker build -t circleci/elasticsearch .
Sending build context to Docker daemon 57.86 kB


Sending build context to Docker daemon 

Step 0 : FROM dockerfile/java:latest
Pulling repository dockerfile/java

docker build -t circleci/elasticsearch . returned exit code 1

INFO[0000] Error: image dockerfile/java:latest not found Action failed: docker build -t circleci/elasticsearch . 
```

**Comment by webwurst** [comment]
The Dockerfile looks quite outdated. If the content from [docker-library/elasticsearch](https://github.com/docker-library/elasticsearch/tree/master/1.7) would be placed here, it might just work.

**Comment by bellkev** [comment]
Sorry about that. Should be fixed now.
